#Database Properties.
spring.application.name=springboot_jpa_emp_details_demo
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Admin

#Query trace
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

